### ISSUE TITLE
Type mismatch warning

### ISSUE THREAD

**Issue by rogeriodec** [Kampfkarren/Roblox#104]
I think this has to do with the last update to Roblox Studio (440), because before this warning did not appear.
I also opened several backup versions of my project and the same warning appears on all versions.
In any case, this appears now:

```
ServerScriptService.DataStore2
W000: (500,28) Type mismatch { ClearCache: (} -> any, Combine: (any, free750-7-0) -> any, Constants: any, PatchGlobalSettings: (any) -> any, SaveAll: (any) -> any, __call: (any, any, any) -> any } and (any, any) -> (any, free748-7-0)
W000: (495,21) Type mismatch { ClearCache: () -> any, Combine: (any, free739-4-0) -> any, Constants: any, PatchGlobalSettings: (any) -> any, SaveAll: (any) -> any, __call: (any, any, any) -> any } and (any, any) -> (any, free737-4-0)
```
![image](https://user-images.githubusercontent.com/11199752/87796248-79217a80-c81f-11ea-8e2c-9b7406311c9b.png)

In time: this warning appears only when the game is NOT running on Studio. When running, it dissapear.

**Comment by Kampfkarren** [comment]
Is this on the latest GitHub release? The line numbers seem off to me.

**Comment by rogeriodec** [comment]
Yes, I got it 1 week ago...
Double-clicking on the warning, it open this:
![image](https://user-images.githubusercontent.com/11199752/87831060-d84fb100-c858-11ea-83cc-929608ec61a2.png)

**Comment by Kampfkarren** [comment]
Yeaaaah, I have no idea what that's about. I don't see any issues with types there.

**Comment by rogeriodec** [comment]
This warning is shown in the Beta "Script Analysis" and after Studio 440 update. Have you enabled it and also didn't get the same warning there? Of course, it's just a warning, but normally Script Analysis is very precise and could indicate some missed declaration or something else...
Anyway, I also opened a topic in Studio Bug on Roblox Devforum but as always, waiting for a long time to be viewed by them...

**Comment by rogeriodec** [comment]
I think I know the problem in the code:

Script Analysis Beta shows the "Type Mismatch" warning because "DataStore2" is actually being declared as an array:

![image](https://user-images.githubusercontent.com/11199752/88687047-27ee7200-d0ce-11ea-93f0-8ee5d84b1558.png)

If you "Go to declaration":

![image](https://user-images.githubusercontent.com/11199752/88687150-4a808b00-d0ce-11ea-8edb-06d5c1861620.png)

Here is what it finds:

![image](https://user-images.githubusercontent.com/11199752/88687211-5ff5b500-d0ce-11ea-9d7c-5143b4ce33eb.png)

How to solve this issue?

**Comment by rogeriodec** [comment]
Nevermind, it was confirmed it's not a problem with DataStore2 (https://devforum.roblox.com/t/how-to-fix-this-type-mismatch-in-datastore2/696686/7?u=rogeriodec_games).
