### ISSUE TITLE
:GetTable() also getting the table in the parameters, even though the player is the second time player

### ISSUE THREAD

**Issue by TheLegend192** [Kampfkarren/Roblox#106]

**Comment by TheLegend192** [comment]
I have the table that took some default placement for new players, when the new player joins, the game will set up for first time player. but when the player rejoin the game, they got the default table, and their own table.

**Comment by Kampfkarren** [comment]
I have no idea what this is reporting. Can you provide a code example, what is happening, and what you expect?

**Comment by TheLegend192** [comment]
ok so I get player saved data, this is placement data
function remotes.DSPlacement.OnServerInvoke(player)
	local tycoonObjects = DataStore2("TycoonObjects",player)
	return tycoonObjects:GetTable({
		--[[
		["-7, 2, 9, 0, 0, -1, 0, 1, 0, 1, 0, 0"] = 1,
		[" -7, 2, 1, 0, 0, 1, 0, 1, 0, -1, 0, 0"] = 1,
		["-11, 2, 1, 0, 0, 1, 0, 1, 0, -1, 0, 0"] = 1,
		["-11, 2, 9, 0, 0, -1, 0, 1, 0, 1, 0, 0"] = 1,
		[" 23, 2, -25, -1, 0, 0, 0, 1, 0, 0, 0, -1"] = 6,
		]]
	})
end

so when the player first join, the above is their data

and then the player will do some thing like placing and deleting

then I save the table when player leave

Now the player joined, the player get the data of theirself AND the data for new player.

**Comment by Kampfkarren** [comment]
Yeah, that's what :GetTable is meant to do. If you don't have any of the keys it has, then it'll add them. Are you sure you didn't just want `:Get` instead?

**Comment by TheLegend192** [comment]
wait, so It's a feature?, does Get work with table?, ok so I am a bit confused there sorry

**Comment by TheLegend192** [comment]
yup, I will close it
