### ISSUE TITLE
Upgrade to roblox-lua-promise v3.0.1

### ISSUE THREAD

**Issue by evaera** [Kampfkarren/Roblox#109]
https://github.com/evaera/roblox-lua-promise/security/advisories/GHSA-mq7h-vf5c-52f4

### Impact
`Promise.delay`'s internal thread scheduler has a bug in v3.0.0 that can cause `Promise.delay` to **error** which can interrupt the Promise chain with errors escaping the Promise library.

`Promise.is` would return false for Promises created with roblox-lua-promise@v2 which would break some APIs when passing Promises to things like `Promise.all`.

### Patches
Upgrade to version v3.0.1 which fixes these issues.

### Workarounds
There are no good ways to work around these issues.

**Comment by Enderxcthz** [comment]
please no promises are terrible D:

**Comment by Kampfkarren** [comment]
@Enderxcthz We already use promises extensively both internally and in user facing places. This isn't a feature request, it's a security patch.

**Comment by Enderxcthz** [comment]
I pitch we remove promises all together, no need for security with something that doesn't exist 😎

**Comment by Kampfkarren** [comment]
If you're not going to be productive then you're not going to be allowed to comment.

**Comment by Darkshepherd** [comment]
I submitted a pull request with the latest Promise.lua file. This is my first contribution so I don't know if I did it right. I hope it is helpful.

I tested this with the latest DataStore2 code on my local machine and everything seems fine. I don't know why the automated selene check failed. You can delete my pull request and use your own if you want.

Thanks for DataStore2. This module has been very helpful and I love it.
