### ISSUE TITLE
:Get(defaultValue) doesn't save the default value unless it's set again.

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/Roblox#11]
Say you had the code:

`dataStore:Get(10)`

If the player had no data, they'd get "10". Say a player leaves after this and :Set is never called. This data won't save. This doesn't really matter until you change the default value, say:

`dataStore:Get(20)`

Now all players who used to have 10 and whom :Set was never called will now get 20.

This is a niche edge case that probably doesn't matter all too much, but it's surprising.

**Comment by visskiss** [comment]
This is not a bug. No one would expect a "Get" function to "Set" anything.  If you want to set the player's value, then a Set should be called after the get, otherwise, this behavior is expected.

**Comment by Kampfkarren** [comment]
That's fair. I was sitting on this issue for a bit since I don't know if it's truly in the best interest to change the behavior. Closing.
