### ISSUE TITLE
Can't debug while using DataStore2

### ISSUE THREAD

**Issue by rogeriodec** [Kampfkarren/Roblox#115]
Could you help me?
This problem occurs only when using DataStore2.
I have an [open ticket at Roblox DevForum](https://devforum.roblox.com/t/not-running-script-because-past-shutdown-deadline-x8-after-30-seconds-when-stopping-a-debug/713981) for over 3 months, but as much as I beg, they are not paying attention.
In summary, every time I start debugging and then I stop the debug, Studio freezes for 30 seconds.
I tried to trace the problem within the DataStore2 code, but I don't have enough knowledge to do so.
The only thing I know is that when I disable DS2, the problem goes away.
Could you help me?
How can I send you the original file to test, in a private message?

**Comment by Kampfkarren** [comment]
The solution is to enable Studio API access--DataStore2 currently does not support a place without this option as I've never needed this.

**Comment by rogeriodec** [comment]
This option has always been enabled; without it, DataStore does not work.

![image](https://user-images.githubusercontent.com/11199752/99316237-c1d75780-2842-11eb-9d81-b146b3aa8473.png)

It's not that problem, but, as I said, the problem is that Studio freezes 30 seconds when I stop debugging.
And, as I said earlier, this only happens when I'm using DataStore2.
Could you help find a solution?

**Comment by Kampfkarren** [comment]
I'm really not sure as I've never had this happen to me, but this sounds awfully familiar to the old `:BindToClose` issue.

Your best bet is to see if you can identify this as a Roblox bug with a minimal repro, as DataStore2 is very complex.

**Comment by rogeriodec** [comment]
In [this post](https://devforum.roblox.com/t/not-running-script-because-past-shutdown-deadline-x8-after-30-seconds-when-stopping-a-debug/713981/10?u=rogeriodec_games) of the same OP, I show the line error, it's a Roblox internal script, but it's being activated by DataStore2.
Could I send you the original project?
I think it would be faster for you to see the problem.

**Comment by Kampfkarren** [comment]
Ah, I think I might know what the problem is. Send me and I can try to take a look, though I am focusing a lot of my time on non-DataStore2 related projects right now.

Most likely it's due to the stupid hack we use where we set `player.Parent = nil` when they leave (or maybe just on BindToClose? I forget).

**Comment by rogeriodec** [comment]
How can I send you the file in privante?

**Comment by Kampfkarren** [comment]
Send me a message on the dev forums (@Kampfkarren).

**Comment by rogeriodec** [comment]
I just sent the file

**Comment by Kampfkarren** [comment]
Going to mark this as a Roblox issue since DataStore2 can't really function without BindToClose.
