### ISSUE TITLE
Add the option to :Save() and not make a new backup

### ISSUE THREAD

**Issue by LucasMZReal** [Kampfkarren/Roblox#123]
Not sure if that's a thing, or if that's how :Save() works, but I would like a option on which you can replace the newest backup with the new data instead of creating a new backup.

**Comment by Kampfkarren** [comment]
:-1: I'm not interested in exposing the implementation details of saving methods any more than I already have. I don't think this provides any benefit, and I already think you should be using Standard instead of OrderedBackups instead.
