### ISSUE TITLE
Memory leak per player

### ISSUE THREAD

**Issue by chess123mate** [Kampfkarren/Roblox#124]
In [DataStore2/init.lua:549](https://github.com/Kampfkarren/Roblox/blob/4fd9ed37edfbc9ef1f54c2dd9d0564fd12a557b4/DataStore2/init.lua#L549) keeps the bound function in memory for the rest of the server's lifetime, along with everything needed to let the function run (the `player` instance and `datastore` table).

**Comment by fnuerpod** [comment]
Issue resolved - should be closed?
