### ISSUE TITLE
DataStore2 breaks some scripts that use game:BindToClose()

### ISSUE THREAD

**Issue by angeld23** [Kampfkarren/Roblox#125]
I've noticed that DataStore2 uses `game:BindToClose()` (line `542` in the main module) to set every player's parent to `nil` upon the server being shut down.

```lua
game:BindToClose(function()
    if not fired then
	    spawn(function()
		    player.Parent = nil -- Forces AncestryChanged to fire and save the data
	    end)
    
	    event.Event:wait()
    end
    
    local value = dataStore:Get(nil, true)
    
    for _, bindToClose in pairs(dataStore.bindToClose) do
	    bindToClose(player, value)
    end
end)
```

This works on its own to force the game to save player data, but it also breaks other scripts that may use `game:BindToClose()`. For example, our game has a "soft shutdown" script that binds a function to teleport all the players to a new server and yield until all Players have left. With DataStore2, all the players are instantly removed and it thinks that everyone has left, shutting down the game before the players can even teleport.

Is there some other way you could force players' data to be saved _other_ than this strange solution?

**Comment by Kampfkarren** [comment]
> Is there some other way you could force players' data to be saved other than this strange solution?

Yes. This was a very dumb solution.
