### ISSUE TITLE
DataStore2 hasn't had a GH release (whether pre-release or not) in just under 1.5 years.

### ISSUE THREAD

**Issue by ThatOneCoderUwU** [Kampfkarren/Roblox#127]
Additionally, the [ROBLOX Library version](https://www.roblox.com/library/1936396537/DataStore2-Data-Loss-Prevention-and-Caching) hasn't been updated in a year.

**Comment by Kampfkarren** [comment]
The Roblox library version is impossible to update due to bugs with Roblox, and is no longer officially supported anywhere.

I think the concern with a new release is there's some breaking behavior with :Set yielding if its the initial call. I made a broad poll asking if this would break anyone's code and got mixed results, though I'm honestly not sure how much I believe that.

**Comment by nootkroot** [comment]
I know this thread is months old but when will there be new new release? Maybe only a beta (use at your own risk) release? Cause I see things being changed but no real update.

**Comment by Kampfkarren** [comment]
I can possibly do a beta release, but I don't have the bandwidth to fix the backwards incompatible bug that prevents a real release.

**Comment by nootkroot** [comment]
Maybe start a new repo or branch for the newer version and just do bug fixes and stuff to the old version? Idk I would just really like to have a newer version of DataStore2 since I haven't started any projects with it myself yet and I wouldn't want these compatibility issues either.

**Comment by Kampfkarren** [comment]
I don't plan on making any more large updates to DataStore2, I have a new, more advanced, data store library I want to make once we actually get to it into our production schedule.

**Comment by nootkroot** [comment]
Do you have any plans on an estimated release date? Not trying to pressure you or anything I just want to have an effective database system and think that your ideas on how to make one are good. Also, are you planning on making the new version compatible with the Datastore Editor plugin or will it be the same method as DataStore2? Thanks!

**Comment by Kampfkarren** [comment]
There's a PR right now that I need to look at, will probably do so on Saturday.

> Also, are you planning on making the new version compatible with the Datastore Editor plugin or will it be the same method as DataStore2? 

It's basically the exact same thing, except with a slight quirk if you're using DataStore2 wrong-ish. You're able to use it now if you build it yourself, even.

**Comment by Kampfkarren** [comment]
Oh, if you meant of my new system, no I have no ETA, and it will just use standard data stores--not the method DataStore2 uses.

**Comment by nootkroot** [comment]
Could you please explain how I could build it myself? I'm not talking about the new system btw. Also, what are the major differences between the latest release in the release and the "new version" your talking about? How would it break the old version? Thanks!

**Comment by Kampfkarren** [comment]
I linked a blog article earlier explaining it. 

To build yourself, you can use Rojo and `rojo build DataStore2.project.json -o DataStore2.rbxm` IIRC.

**Comment by Kampfkarren** [comment]
https://github.com/Kampfkarren/Roblox/releases/tag/ds2-1.4.0
