### ISSUE TITLE
Developer Products queue in datastore

### ISSUE THREAD

**Issue by jareer12** [Kampfkarren/Roblox#128]
Hi, Owner of DataStore2,

I've been facing this error from DataStore2 of a developer product, so I recently migrated from DataStoreService to DataStore2 and I'm receiving this error:
` DataStore request was added to the queue. If the request queue fills, further requests will be dropped. Try sending fewer requests.Key = player_1877006416_product_1160570352 ` no idea why its queueing all the developer products requests but not the cash update the cash update works fine and so good!
![image](https://user-images.githubusercontent.com/57962439/112770071-15de1e00-9025-11eb-8652-1d4e44ba567e.png)

**Comment by jareer12** [comment]
By the way heres the leaderboard code:
` local Players = game:GetService("Players")
local ServerScriptService = game:GetService("ServerScriptService")
local DataStore2 = require(ServerScriptService.DataStore2)

DataStore2.Combine("DATA", "cash")

Players.PlayerAdded:Connect(function(player)
	local CashStores = DataStore2("Cash", player)

	local leaderstats = Instance.new("Folder")
	leaderstats.Name = "leaderstats"

	local cash = Instance.new("NumberValue")
	cash.Name = "Cash"
	cash.Value = CashStores:Get(0)
	cash.Parent = leaderstats
	leaderstats.Parent = player

	CashStores:OnUpdate(function(NewCash)
		cash.Value = NewCash
	end)

	local CashStores = DataStore2("Cash", player)
	-- Store:Increment(1) -- Just Gives Play "1" Cash When They Join
end)
`

**Comment by Kampfkarren** [comment]
Looks like you have an ordered data store elsewhere--where is this product_##### data store?

**Comment by jareer12** [comment]
> Looks like you have an ordered data store elsewhere--where is this product_##### data store?

So is there a way I can clear or remove the old DataStore I'm getting 1000+ requests per minute?

![image](https://user-images.githubusercontent.com/57962439/112794580-624a4d80-9067-11eb-8d75-13eb03f608f5.png)

**Comment by jareer12** [comment]
heres my Cash Purchase script (connected) to a Gui:

```local ServerScriptService = game:GetService("ServerScriptService")
local DataStore2 = require(ServerScriptService.DataStore2)
local MPS = game:GetService("MarketplaceService")
local Players = game:GetService("Players")

--[[
MPS.ProcessReceipt = function(receiptInfo)
	print("Running Bough Cash Script...")
	local player = game.Players:GetPlayerByUserId(receiptInfo.PlayerId)
	local Store = DataStore2("Cash", player)
	if receiptInfo.ProductId == 1160570352 then -- 50 CASH DEV PRO
		print("Player Bought 50 Cash")
		Store:Increment(50)
		return Enum.ProductPurchaseDecision.PurchaseGranted
	elseif receiptInfo.ProductId == 1160570424 then -- 100 CASH DEV PRO
		Store:Increment(100)
		print("Player Bought 100 Cash")
		return Enum.ProductPurchaseDecision.PurchaseGranted
	elseif receiptInfo.ProductId == 1160570498 then -- 250 CASH DEV PRO
		Store:Increment(250)
		print("Player Bought 250 Cash")
		return Enum.ProductPurchaseDecision.PurchaseGranted
	elseif receiptInfo.ProductId == 1160570583 then -- 500 CASH DEV PRO
		Store:Increment(500)
		print("Player Bought 500 Cash")
		return Enum.ProductPurchaseDecision.PurchaseGranted	
	end
end
]]--```

**Comment by Kampfkarren** [comment]
As is recommended in the documentation, new data should be using the Standard data stores.

Your console suggests you are using an ordered data stores outside of DataStore2, since that key is not in your data store, which you should not be doing *unless* you are using Standard.

**Comment by jareer12** [comment]
> As is recommended in the documentation, new data should be using the Standard data stores.
> 
> Your console suggests you are using an ordered data store
 outside of DataStore2, since that key is not in your data store, which you should not be doing _unless_ you are using Standard.

I changed the `OrderedBackups` to `Standard` saving method but it still queues stuff.
![image](https://user-images.githubusercontent.com/57962439/112797908-66c53500-906c-11eb-84d8-fdd58b643654.png)

**Comment by Kampfkarren** [comment]
The things that are queueing are not DataStore2 instances, according to the log you posted.

**Comment by jareer12** [comment]
What can they possibly be?
I tried commenting everything in the purchase script remove the
`Get("DataStorageService")` from all scripts then why is it doing so?

**Comment by Kampfkarren** [comment]
"player_xxx_product_xxx" is not something DataStore2 can produce if you are combining all keys, it is not a valid DataStore2 key.

**Comment by jareer12** [comment]
> "player_xxx_product_xxx" is not something DataStore2 can produce if you are combining all keys, it is not a valid DataStore2 key. Therefore, it is not a bug with DataStore2.

so I tried removing all the scripts from ServerScriptService and played the game but it still gives the same error... Plus I haven't called the script anywhere else except ServerScripts.
