### ISSUE TITLE
Give Player Cash Admin Panel -  DataStore2

### ISSUE THREAD

**Issue by jareer12** [Kampfkarren/Roblox#129]
Hello, Kampfkarren!

So, I'm making a game and I want to add a feature and from an admin GUI we (admins) can give player cash and it stores it to the DataStore, whats the process to make that if you can explain?

**Comment by Kampfkarren** [comment]
This isn't really the place for support questions like this. Please read the documentation for the answers to your question, this is a very trivial one. Note that it is not possible with DataStore2 alone to modify data of players not in game.
