### ISSUE TITLE
Script with BindToClose callback was destroyed; callback cannot be called!

### ISSUE THREAD

**Issue by CodEdRoblox** [Kampfkarren/Roblox#135]
This happened when i try to save new table (i already used tables for other type of inventory and i know how to create it). I even tried to save on new id, it says "player left, saved DATA" but not the "player left, saved INVENTORY", instead it says error in title when server is shutdowned.
Sorry if my english is bad.
![image](https://user-images.githubusercontent.com/85065491/120207507-42f2bb00-c278-11eb-9d11-1cb5e2a76d35.png)

**Comment by Kampfkarren** [comment]
Does this happen without you making your own BindToClose?

**Comment by CodEdRoblox** [comment]
> Does this happen without you making your own BindToClose?

No, i never used this function. Only DataStore2 was using it.
![image](https://user-images.githubusercontent.com/85065491/120301864-075bfd80-c319-11eb-929f-dc88f3a5b5ee.png)

**Comment by Kampfkarren** [comment]
Are you destroying your script that calls DataStore2? Where is it? If it's inside something like a character, then that might be the cause of the error.

**Comment by CodEdRoblox** [comment]
Thanks! Now it works.
