### ISSUE TITLE
Introduction of new game that uses DataStore2 to the Documentation website

### ISSUE THREAD

**Issue by GabrielHoy** [Kampfkarren/Roblox#146]
I'm the owner of a game called ZOぞ with ~60M visits, and I can confirm that we do use DataStore2 as the main framework for data saving. ZOぞ may be a good game to add to your website and I would love to see it posted on a popular framework like DS2.

Game link:
https://www.roblox.com/games/6678877691/ZO-WIP?refPageId=6a3bbec4-a813-402c-858d-0e25cf3d5538

**Comment by Kampfkarren** [comment]
Neat!

You can edit this file to include it: https://github.com/Kampfkarren/Roblox/blob/master/docs/index.md
