### ISSUE TITLE
Data not loading the most recent version across places

### ISSUE THREAD

**Issue by sev1nty** [Kampfkarren/Roblox#148]
Saving data in an individual place works, but if you change the data then join a separate place (in the same game), it seems to load a backup/previous version of the datastore.

**Comment by Kampfkarren** [comment]
Are you saving before teleporting? We don't get this issue in Zombie Strike.

**Comment by sev1nty** [comment]
It just says this when a player leaves. It works fine in one place, and not the other:
![image](https://user-images.githubusercontent.com/71786526/137180829-96b5eb07-fca1-49f0-9fa7-03bb904909b9.png)

**Comment by Kampfkarren** [comment]
There's not really any way for me to see this as a DataStore2 bug--your error shows that you are trying to save instances, which you can't save in data stores. Saving across places also provably works, if you're saving before teleporting.
