### ISSUE TITLE
Complete data loss when joining a private server

### ISSUE THREAD

**Issue by Sxribe** [Kampfkarren/Roblox#152]
We're experiencing an issue where players' data gets wiped the second they join a private server (for example, their cash gets set to the default of $100). We haven't tinkered with any datastore code recently, so I'm not sure where to even begin figuring this out - there isn't a single error in the log upon join (I assume the issue must occur then, as data seems to get reset then).

The weirder thing is that its not all of the player data that is being reset. Cash/XP get reset while things like Skins remain unaffected. (We do `.Combine()` everything, so that makes this even weirder.

Any ideas on what could be causing this, or where to even begin debugging this?

**Comment by Sxribe** [comment]
Not too familiar with the internals of DS2, but could this be related somehow to the player's data not being correctly retrieved with `:Get()` for whatever reason (through error or whatever), and then `defaultValue` is being written/used in the datastore? If `:Get()` fails, would that write itself to the database if we aren't using `:SetBackup()`?

**Comment by Kampfkarren** [comment]
Not sure what that last question means.

`:Set()` can be run without a `:Get()` ever occurring, which could potentially overwrite data, but `:Get()` will never return if data stores are down AND if backups are not enabled.
