### ISSUE TITLE
Is it possible to realize the table structure by combining multiple times?

### ISSUE THREAD

**Issue by Water-comfortable** [Kampfkarren/Roblox#153]
Suppose you have two axes in your backpack, and each axe has a different durability (the axe will disappear when the durability becomes zero).
I try to use datastore2 to save the data.
The first step is `DataStore2.Combine("Data", "Axe")` .
But in the second step, I can only set a value for the axe, which is used to represent the number or durability or ID. 
I have to use ID to track different states.
Like the title, can I combine multiple layers? Or other solutions?
I noticed that you said that the table is unnecessary, what should I do? please help me.
![issue2](https://user-images.githubusercontent.com/50854213/142597377-84882f87-99d3-4ebb-8694-85f54ce96f00.PNG)

**Comment by Kampfkarren** [comment]
Not natively, Combine is really just a means to avoid the data store throttle. This would be pretty jank anyway.

**Comment by Water-comfortable** [comment]
> Not natively, Combine is really just a means to avoid the data store throttle. This would be pretty jank anyway.

Is datastore2 only used to record values such as the number of gold coins, hp, whether you have specific equipment, etc.? If one item correspond to multiple states that cannot be used in datastore2?

**Comment by Kampfkarren** [comment]
You can read them fine. Just get the key and interact on the table like you would anything else.

**Comment by Water-comfortable** [comment]
> You can read them fine. Just get the key and interact on the table like you would anything else.

Thanks for your reply, I will try my best.
