### ISSUE TITLE
Use other Keys than player

### ISSUE THREAD

**Issue by ModProgrammMiked** [Kampfkarren/Roblox#155]
I know it sounds dumb, but why can we only use the Player for Datastore2()? Why can't we use like tags, or UserIds? Would be nice if we would get it! :D

**Comment by Kampfkarren** [comment]
There's an open issue for user IDs, but read only. The problem is it's not safe. DataStore2 caches, and so multiple separate instances can end up clashing different data against each other.

**Comment by ModProgrammMiked** [comment]
But that would just be dependant on the use, errors are not your problem if they happen. I mean, you can just support players as safe and other keys as "unsafe" too

**Comment by Kampfkarren** [comment]
I'm not personally interested in adding footguns to DataStore2 given its popularity, though I would encourage you to fork if you need this.
