### ISSUE TITLE
` ServerScriptService.DataStore2:485: DataStore2() API call expected {string dataStoreName, Player player}, got {string, nil} `

### ISSUE THREAD

**Issue by madepossibleby** [Kampfkarren/Roblox#165]
I'm getting this error.
.__call (the function on the line erroring) isn't being called or mentioned in any scripts.
How do i fix this?
` ServerScriptService.DataStore2:485: DataStore2() API call expected {string dataStoreName, Player player}, got {string, nil} `

**Comment by Kampfkarren** [comment]
You aren't passing in a player. Check your code.

**Comment by madepossibleby** [comment]
Ah, my bad, used a variable which was nil when getting the datastore.
