### ISSUE TITLE
Im confused

### ISSUE THREAD

**Issue by KarenMarin** [Kampfkarren/Roblox#170]
Hello, I'm sorry if I'm using the wrong place to ask this question, but I can't comment on the roblox forum, I don't have that permission, anyway...

My big question is: I was reading about what I got from DataStore2 and I would like some clarification on which I should use -> require(1936396537) or require(ServerScriptService.DataStore2)

I'm currently using the second option(require(ServerScriptService.DataStore2)), is there a problem with continuing with it?

If I choose to use require(1936396537) can I delete the DataStore2 module from ServerScriptService?

**Comment by Kampfkarren** [comment]
You should never require anything by ID ever.
