### ISSUE TITLE
Saving to a table

### ISSUE THREAD

**Issue by Yakend-bit** [Kampfkarren/Roblox#180]
Hi, I'm very new to ROBLOX development, so I'm not *really* versed on how to properly use this tool. However, it does greatly benefit me.

I'm trying to clean up a script I feel I made in a bit of a short-sighted way, you can check it out here if you want: 

Anyway, my desire now is to at least contain all of the stats into their own table, so I can have an easier time creating new stats and managing the current ones.

```lua
local Players = game:GetService("Players")
local ServerScriptService = game:GetService("ServerScriptService")
local Workspace = game:GetService("Workspace")

local DataStore2 = require(ServerScriptService.DataStore2)
local myTablePart = Workspace.Table.ClickDetector

-- Combine every key you use. This will eventually be the default, but for now read the "Gotchas" section to understand why we need this.
DataStore2.Combine("DATA", "tableStore")


Players.PlayerAdded:Connect(function(player)
	local UserData = player:WaitForChild("UserData")
	local storage = DataStore2("tableStore", player)
	storage:Get({
		myTableFirst = "Joe",
		myTableSecond = false,
		myTableThird = 3,
		myTableFourth = {}
	})
	while true do
		task.wait(8)
		local myTable = DataStore2("tableStore", player)
		local secondObj = myTable.value.tableStore.myTableSecond
		print(myTable)
	end
end)

myTablePart.MouseClick:Connect(function(plr)
	local myTable = DataStore2("tableStore", plr)
	local secondObj = myTable.value.tableStore.myTableSecond
	secondObj:Set(true)
end)

```

This simply doesn't work at all, at least not with the way I want. My logic was I could index the exact thing I want and then set its data that way, but I just get an error for attempting to index a boolean, which I don't really understand. My _intention_ is to index the boolean and then to change it, I don't know why this wouldn't work.

I know DataStore2 has the logic to support tables and create tables, so therefore it must have the logic to save to specific index's, but there isn't any documentation I can find. I searched the API for something to do with setting specific table info apart from the creation of the datastore and I can't find a thing.

Anyway, how do I set data to specific index's in a table? Is it not possible to do this? I understand that ultimately DataStore 2 is putting everything in one big table on the backend, it's all within "value", so technically it's all one big data store anyway, I would just like the freedom to be able to write it out in a table and be able to save to specific index's.

**Comment by Kampfkarren** [comment]
This simply is not how you use DataStore2. `myTableSecond:Set(true)` *can't work* because Get and Set are only on the DataStore2 object itself.

Furthermore, DataStore2 removes the need for these "bundles of data" tables, since the `Combine` **is** what makes it all one table!
