### ISSUE TITLE
DataStore2 - OnFail

### ISSUE THREAD

**Issue by CleverSource** [Kampfkarren/Roblox#19]
A .OnFail for DataStor2 so if it fails to save data you can do something such as notifying the client.

**Comment by CleverSource** [comment]
No clue but I'd prefer something that directly only gives errors.

**Comment by Kampfkarren** [comment]
Closing since I feel manual error handling is a better alternative.

**Comment by Kampfkarren** [comment]
:Save() will error if it fails, so just pcall your :Save().
