### ISSUE TITLE
DataStore3

### ISSUE THREAD

**Issue by CleverSource** [Kampfkarren/Roblox#30]
Okay, I don't expect you to do this as DataStore2 is already awesome. But it would be amazing to see a DataStore3 with berezaa's new system. You can read exactly what he said [here].

Reference image:
(https://twitter.com/berezaagames/status/1122174490882998272)
![image](https://user-images.githubusercontent.com/21996470/56857242-0fc2fc80-6939-11e9-88e4-38b7a9c7b834.png)

I would love to see you implement this. If you did I would recommend just strictly putting it into DataStore2 but leaving DataStore3 options under a "beta" flag and it will be completely optional and eventually be forced?

**Comment by CleverSource** [comment]
On the image, the left is how DataStore2 works (berezaa's initial idea) and the right is his new system.

**Comment by Kampfkarren** [comment]
The one on the left works fine for what I need, and fiddling with different data store solutions is dangerous. Closing as out of scope.
