### ISSUE TITLE
Rename everything to .lua and give DataStore2 its own folder

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/Roblox#34]
Rotriever does not seem to support monorepos like this, so DataStore2 will have to be given special treatment. Also, `.module.lua` is an ancient file naming that has been superceded by simply `.lua` for a while.

**Comment by Dog2puppy** [comment]
Where are the docs for Rotriever?

**Comment by Kampfkarren** [comment]
Nowhere, it's not even available to the public yet. You can figure out generally what you're meant to do to use it though from repositories from Roblox engineers like https://github.com/osyrisrblx/t

**Comment by sayhisam1** [comment]
At the very least, renaming the repo something else seems like a wise choice.
The name "Roblox" as a repo isn't really illuminating as to what this is, and indeed, I have gotten confused myself several times by it.
