### ISSUE TITLE
Data being reverted to a previous save when shutting down servers

### ISSUE THREAD

**Issue by Intrance1** [Kampfkarren/Roblox#45]
After doing some testing, I think what's happening is when a game server is shutdown, the player's data is reverted back to the data received from the initial :Get() when the player joined the server, ignoring any changes made to the player's data while in the server.

**Comment by Kampfkarren** [comment]
Can you try this and see what happens (best if it works on a slightly modified baseplate):

- Join server
- Change data in some way so that it actually saves
- Shut down all servers
- Quickly join back
- Observe your data is the old data
- Do NOT change your data
- Leave, it won't save if data isn't changed
- Join back later

What data do you get? Old data or the data from when you shut down? My theory is it's still saving by the time people rejoin.

**Comment by Intrance1** [comment]
I followed the steps and got the old data.

**Comment by JustMikami** [comment]
i just started using datastore2 and having the same problem i currently have a game with 500+ playing and they lose data when i shutdown the server or lose connection how could i fix this?

**Comment by JustMikami** [comment]
i just started using datastore2 and having the same problem i lose data when i shutdown the server or lose connection how could i fix this?

**Comment by Kampfkarren** [comment]
@Intrance1 That's strange--and it says in the console it didn't save because of unchanged data, correct? DataStore2 runs code on BindToClose, so there could be something incorrect there.

**Comment by Intrance1** [comment]
There's nothing in the log after the game is shutdown. I'm not sure if messages continue to be posted to the console after the server is shutdown. The message could be posted after I'm kicked from the server and that could be why I don't see anything in the console.

**Comment by Kampfkarren** [comment]
Can you see what happens when you add this somewhere in your code:

```
game:BindToClose(function()
    dataStore:Save()
end)
```

I wonder if it's a BindToClose problem or a DataStore2 problem.

**Comment by Intrance1** [comment]
That worked. I shutdown the server and "saved key" outputted in the console, rejoined and had the correct data.

**Comment by Kampfkarren** [comment]
Strange, that means it must be an issue with how DataStore2 specifically implements it. Not so coincidentally, there's also no unit tests for it.

Here's the relevant lines:

https://github.com/Kampfkarren/Roblox/blob/56a0d27a392a9d71de1af6f3f2020616a1ab5208/DataStore2/init.lua#L619-L644

It's a bit weird, but the gist of it is:

- When the player leaves (ancestry changed and they're no longer in the data model), set a "fired" flag to true after it has been saved and fire an event.
- On BindToClose, if the player hasn't successfully saved yet (the "fired" flag), wait for them to save.

This logic makes sense to me, so I'm not sure why it isn't working. While we could just call `:Save()` twice, this would fire *two* requests to save the data, which would add additional overhead.

**Comment by Intrance1** [comment]
So I was doing some testing with the playerLeavingConnection and I think the problem is with the AncestryChanged event. I replaced it with a PlayerRemoving event and that worked.

**Comment by Kampfkarren** [comment]
That must be it, the AncestryChanged patch is recent: https://github.com/Kampfkarren/Roblox/commit/620688eae9fea274f1d03e38d189266c261974ca

Thanks for you research! I'll fix it when I can unless you want to make a stab at a PR.
