### ISSUE TITLE
DataStore:AfterInitialGet()

### ISSUE THREAD

**Issue by insertLenny** [Kampfkarren/Roblox#73]

**Comment by tomglenn** [comment]
This would be very useful. Any update on this?

**Comment by Kampfkarren** [comment]
My projects tend to move with me, meaning that if I don't need a feature I don't really tend to work on it. PRs are open, however.

**Comment by gabrielvip5** [comment]
ok im sorry

Kampfkarren <notifications@github.com> escreveu no dia quinta, 11/06/2020
à(s) 02:16:
