### ISSUE TITLE
DataStore2 Hangs For 10-30 Seconds | Solution

### ISSUE THREAD

**Issue by NxtGenCode** [Kampfkarren/Roblox#78]
People have been having this issue while testing their game in the studio when using DataStore2 causing a lot of development time loss while testing their game. Please Update The DataStore2 file with this fix.

**_On Line 552 In DataStore2.lua you'll find this bit of code:_**
`game:BindToClose(function()`

**_Above that add this condition statement_**
`if not game:GetService("RunService"):IsStudio() then`

**_Don't forget to close the statement after the BindToClose Event!_**

**Comment by Kampfkarren** [comment]
Roblox fixed this bug.
