### ISSUE TITLE
Cannot load or insert DataStore2

### ISSUE THREAD

**Issue by TheGaelicKing** [Kampfkarren/Roblox#79]
When I attempted to insert DataStore2 into my game, I discovered that the toolbox did not display that I owned the module. However, the Roblox website showed that I did, in fact. DataStore2 is the only item that will never load in studio despite multiple deletions and re-purchases. Nothing I'm doing is working, is this a bug with Roblox or an issue only local to me?

**Comment by Kampfkarren** [comment]
You are describing a Roblox bug that I don't have the power to fix. The model is no longer the recommended version of using the module. Please go to the releases, download the rbxmx there, and put that in your game.
