### ISSUE TITLE
Line 28 - upvalue callback ??

### ISSUE THREAD

**Issue by Cabledragon** [Kampfkarren/Roblox#80]
I keep getting this message while using DS2:
22:27:21.245 - Script 'ServerScriptService.DataStore2.SavingMethods.OrderedBackups', Line 28 - upvalue callback
22:27:21.246 - Script 'ServerScriptService.DataStore2.Promise', Line 218

Should I worry about this, is it breaking everything or are things okay?

**Comment by Kampfkarren** [comment]
It's possible it's just Roblox data stores acting up. Do you have API access on, full team create access, all that stuff?

**Comment by Cabledragon** [comment]
Lol forgot to enable API access, i'm a scrub. sry.
