### ISSUE TITLE
DataStore2:OnUpdate fires twice after combining

### ISSUE THREAD

**Issue by OverHash** [Kampfkarren/Roblox#83]
Minimal repo: https://www.roblox.com/games/4506394655/DataStore2-broken

Code I used: https://gist.github.com/OverHash/e14cdc632829afe83318030a73e4a2dd

Output I receive:
Updating store. Old value was 0
Store updated with new value: 1 (x2)
Updating store. Old value was 1
Store updated with new value: 2 (x2)
Updating store. Old value was 2
Store updated with new value: 3 (x2)

This is firing the OnUpdate function twice

This only occurs after using the DataStore2.Combine function at least once, and from there on it will call the bounded OnUpdate function twice. Adding more combines will not increase OnUpdate firing twice.

**Comment by Quoteory** [comment]
Line 395

function CombinedDataStore:Update(updateFunc)
    self:Set(updateFunc(self:Get()))
    self:_Update() -- change to self:_Update(true) fixes this issue
end

I'm unsure if this has any side effects, I'm fairly new to the code and I was just messing around trying to fix this issue for myself, thought I'd post here in case this is the actual solution
(also not very experienced with Github so sorry if I'm doing something wrong)

**Comment by OverHash** [comment]
This only seems to happen when using `Update`.

```lua
local Players = game:GetService('Players')
local ReplicatedStorage = game:GetService('ReplicatedStorage')

local DataStore2 = require(ReplicatedStorage:WaitForChild('DataStore2'))

DataStore2.Combine('DATA', 'test')

Players.PlayerAdded:Connect(function(player)
	local store = DataStore2('test', player)

	store:OnUpdate(function(value)
		print('Store updated with new value: '..value)
	end)
	
	store:Set(10)
end)
```
only prints once.
