### ISSUE TITLE
:BeforeSave and :SaveAll doesnt seem to be working!

### ISSUE THREAD

**Issue by popgoescreators700** [Kampfkarren/Roblox#87]
I was programming a compacter for my data using a custom function and BitBuffer. This compacter was/is meant to run on BeforeSave and is to uncompact data on BeforeInitialGet. BeforeSave doesnt seem to be ran no matter what i do, but BeforeInitalGet works fine. I am using CombinedStores for the table's keys being accessible to be set without using the whole table to set one key.

I also happened to stumble upon SaveAll not working, and returning an error in my saying that the function doesn't exist outright. I am using the recent version uploaded to the id, so i highly doubt it's the version i am using. Would like this fixed so i can use BeforeSave on my compacter.

I also posted an issue of this on the dev forums with more indepth info, and snippets of my code which i highly doubt it is an issue with, seeing as BeforeSave outright isnt called.

**Comment by Kampfkarren** [comment]
> I also happened to stumble upon SaveAll not working, and returning an error in my saying that the function doesn't exist outright.

Are you doing `DataStore2.SaveAll` or `dataStore:SaveAll()`? Only the former is right, and is not on the version on the free model (which is now deprecated). Download from releases--Roblox does not let me fix the free model.

**Comment by popgoescreators700** [comment]
So, i Did download the release from here, and the SaveAll function works now, but BeforeSave seems to still not work. Even if i run it without the compaction, and just print out the data, it still doesnt print the data.

**Comment by Kampfkarren** [comment]
Can you create a minimum repro code?

**Comment by popgoescreators700** [comment]
Yea sure.

So how i have my system setup is a module is called by one server script and when a player joins a function in that module is called to just initiate all of the events i need, like OnUpdate, and well BeforeSave. The module is close to this, but without any other bit of code that is just to keep things fairly organized for the one script.
```lua
local BBuffer= require(game.ReplicatedStorage.Modules.BitBuffer); --require(174612085);
local Dstore= require(game.ReplicatedStorage.Modules.DataStore2); --require(1936396537);
BBuffer= BBuffer:Create();

local HTTP= game:GetService("HttpService");

local defaultValue= {
	["Coins"]= 50,
	["Credits"]= 5,
	["Inv"]= {},
	["Equipped"]= {
		["MSkin"]= 0,
		["SAbil"]= 0,
		["SPerks"]= {0,0,0},
		["MAbil"]= 0,
		["MPerks"]= {0,0,0}
	}
}

Dstore.Combine("Save","Coins","Credits","Inv","Equipped");

function beforeSaving(o,dat)
	print(dat);
	if type(dat)=="table" then
		dat= HTTP:JSONEncode(dat);
	end
	
	print(dat);
	
	BBuffer:Reset();
	BBuffer:WriteString(dat);
	return BBuffer:ToBase64();
end

function beforeGet(o,dat)
	BBuffer:Reset();
	BBuffer:FromBase64(dat);
	dat= BBuffer:ReadString();
		
	local success,data= pcall(HTTP.JSONDecode,HTTP,dat);
	if success then
		dat= data;
		print(HTTP:JSONEncode(dat));
	end
	
	return dat;
end

local plyer= {};

local module = {};

function module:IsFailed(ply)
	local data= plyer[ply.UserId];
	return data:IsBackup();
end

function module:SetRetries(ply,num,defval)
	local data= plyer[ply.UserId];
	if defval then
		data:SetBackup(num,defval);
	else
		data:SetBackup(num);
	end
end

function module:InitPlayerData(ply,okey)
	local data= Dstore("Save",ply);
	plyer[ply.UserId]= data;
	
	data:BeforeSave(function(dat)
		return beforeSaving(ply,dat);
	end);
	
	data:BeforeInitialGet(function(dat)
		return beforeGet(ply,dat);
	end);
	
	data:OnUpdate(function(dat)
		--Update code.
	end);
end

function module:Get(ply)
	local data= plyer[ply.UserId];
	
	local success,dat= pcall(function()
		return data:GetTable(defaultValue);
	end);
	
	if not success then
		print("Error:",dat);
		return false;
	end
	data= dat;
	
	return data
end

function module:Set(ply,key,value)
	return Dstore(key,ply):Set(value);
end

function module:Save(ply)
	Dstore.SaveAll(ply);
end

return module;
```

**Comment by Kampfkarren** [comment]
That's not much of a minimum repro, what's the smallest code you can write that gets this bug?

**Comment by popgoescreators700** [comment]
So when trying to shrink the code, it seems that BeforeSave isnt called when i use BitBuffer in general, why is this? Is there a certain "execution" time it only allows? When i dont use BitBuffer the BeforeSave Function is executed.

**Comment by popgoescreators700** [comment]
The Module in ServerScriptService is essentially the manager, the code will work, but when you uncomment any code lines (the ones which use/require BitBuffer) it seems to not work anymore.
[Repro.zip](https://github.com/Kampfkarren/Roblox/files/4010687/Repro.zip)

**Comment by popgoescreators700** [comment]
Ok, I think i figured it out!! Appearently Combined stores WONT save a string, and forces you to save data as a table!! This kind of sucks for me, as i really do like the features of being able to easily get data based on the combinedDatastore, but now that i solved it, im actually quite happy!

**Comment by Kampfkarren** [comment]
> Ok, I think i figured it out!! Appearently Combined stores WONT save a string, and forces you to save data as a table!! This kind of sucks for me, as i really do like the features of being able to easily get data based on the combinedDatastore, but now that i solved it, im actually quite happy!

This is not true? I am saving strings and numbers and everything just fine.

**Comment by popgoescreators700** [comment]
Well for some odd reason when running the BeforeSave on the masterkey for a combinedDatastore seems to work if the data returned is a table, and not a string. Hence why BitBuffer didnt work. I also placed some prints in the code specifically when it runs the beforesave function and it prints the savedata as a table and doesnt print the Base64 BitBuffer uses.

Im assuming that this is intended behavior, but maybe it's not? I am honestly confused about how combinedStores work fully, so i am not sure if the BeforeSave has to return a table as the combineStore is essentially a table.

**Comment by Kampfkarren** [comment]
You shouldn't be referencing the master key by name anywhere in DataStore2, that's undefined behavior.

**Comment by Kampfkarren** [comment]
Closing as non-reproducible without undefined behavior.
