### ISSUE TITLE
DataStore2(dataStoreName, player) thinks argument1 (string) is a table

### ISSUE THREAD

**Issue by RealLowPolys** [Kampfkarren/Roblox#88]
I have been unable to figure out an explanation for why this is happening. I've tested by sending different arguments such as numbers and instances, and it correctly displays what I sent. This is my only call, so this is the only spot the error could be coming from. I have used DataStore2 in a past game and never had this issue. 

`local playerData = DataStore2("newData1A", player)`

`ServerScriptService.DataStore2:483: DataStore2() API call expected {string dataStoreName, Instance player}, got {table, Instance}`

**Comment by Kampfkarren** [comment]
That's...extremely strange.

https://github.com/Kampfkarren/Roblox/blob/master/DataStore2/init.lua#L487-L494

All it checks for is `typeof(name) == "string"`. I have no idea.

**Comment by RealLowPolys** [comment]
Yeah I looked at this myself and when I saw it was just a `typeof()` check I got really confused. I think for now I'm just going to comment out the assert to get around this.

**Comment by Kampfkarren** [comment]
Are you doing DataStore2:Combine instead of DataStore2.Combine or something like that?
