### ISSUE TITLE
Non-player data

### ISSUE THREAD

**Issue by awesomebanana2018** [Kampfkarren/Roblox#91]
Add support for data that isn't tied to a player.

**Comment by Kampfkarren** [comment]
What would be the point of this? Where would caching etc come in handy?

**Comment by awesomebanana2018** [comment]
For stuff like global polls or settings. Forgive me if I’m wrong and naïve, I’m kind of new to this.

-Jacob

**Comment by Kampfkarren** [comment]
This doesn't sound like a great use of DataStore2, you wouldn't want this kind of stuff cached since you'd be overriding other servers setting it. You should probably just use normal data stores instead.
