### ISSUE TITLE
Saving time the player leaves?

### ISSUE THREAD

**Issue by RomeoDuncan** [Kampfkarren/Roblox#92]
I have question regarding saving the time the player exits using datastore 2, how would I go about this since it says that you should save data when changes rather than when the player leaves, and also how frequently is the data saved in the game?

**Comment by Kampfkarren** [comment]
DataStore2 automatically saves when the player leaves. DataStore2 only saves when you call :Save() or the player leaves, you yourself can decide auto save times if you want to do that.
