### ISSUE TITLE
Data store was not saved as it was not updated

### ISSUE THREAD

**Issue by MET33** [Kampfkarren/Roblox#94]
datastore2:SaveAll(Player) states- does not save stats as they are not updated
same with :Set()

**Comment by MET33** [comment]
its the newest downloadable version

**Comment by Kampfkarren** [comment]
Yes, if you don't set anything it doesn't save. What's the issue?

**Comment by MET33** [comment]
my issue is when i use Set or SaveAll the game messages me that it doesnt save due do to not updating properly

**Comment by MET33** [comment]
for some reason now the message stopped popping up

**Comment by MET33** [comment]
guess it must have been a random inconsistency
