### ISSUE TITLE
How to modify datastore 2 so it kicks the player if the data is backup?

### ISSUE THREAD

**Issue by RomeoDuncan** [Kampfkarren/Roblox#95]
Hi, I want to modify ds2 so it kicks the player if the data is backup am I doing it correctly below: (Its added in the main module where you have the __call metamethod)
```
	if not DataStoreCache[player] then
		DataStoreCache[player] = {}
	end

	DataStoreCache[player][dataStoreName] = dataStore
	--added this statement
	if dataStore:IsBackup() then
		player:Kick('Failed to load in data')
	end

	return dataStore`

**Comment by Kampfkarren** [comment]
That would work, but data stores go down quite a bit, so make sure this is actually a good idea.

**Comment by RomeoDuncan** [comment]
I'm not sure because I don't want players to be in the game playing thinking that there data is gonna save, but I'll think about it thank you
