### ISSUE TITLE
Update Internal Promise library

### ISSUE THREAD

**Issue by OverHash** [Kampfkarren/Roblox#99]
[Roblox-lua-promise 3.0.0 Release Candidate 1](https://github.com/evaera/roblox-lua-promise/releases/tag/v3.0.0-rc.1) just released. This has many changes that could fix other issues, and is best to stay up to date.

Should DataStore2 update to this new version, even though it is a release candidate?

**Comment by Kampfkarren** [comment]
I'm fine upgrading to anything as long as tests all continue to pass.
